#
# This importer has been disabled. We need fix it before enabling it again.
# There is an error "wrong number of arguments (0 for 2)" when calling it here.
#
# Every hour at the beginning of the hour
# FireArticleImportWorker:
#   cron: "0 * * * *"
#   class: "FireArticleImportWorker"
#   queue: default

# Every hour at the beginning and the middle of the hour
FireArchiveObjectWorker:
  cron: "0,15,30,45 * * * *"
  class: "FireArchiveObjectWorker"
  queue: default

# Every hour at 15 and 45 minute marks
FirePublishObjectWorker:
  cron: "0,15,30,45 * * * *"
  class: "FirePublishObjectWorker"
  queue: default

# At 2:37 in the morning
ChapelImportWorker:
  cron: "37 2 * * *"
  class: "ChapelImportWorker"
  queue: default

# Once a year on April 1st
AnnualCourseFetchWorker:
  cron: "0 0 1 4 *"
  class: "AnnualCourseFetchWorker"
  queue: default
