app:
  name: WCMS
  host: wcms.biola.edu
  relative_url_root:

# Overwrite this in production
secret_token:

urn_namespaces:
- "urn:biola:apps:wcms:"
- "urn:biola:apps:wcms-publisher:"
- "urn:biola:apps:all:"

cas:
  url: "https://login.biola.edu/rubycas"

analytics:
  segment:
    key: # set in settings.local.yml

email:
  enabled: true
  from: no-reply@biola.edu
  developer: appdev@biola.edu
  email_to: # set in settings.local.yml
  smtp:
    server: postfix.biola.edu

elasticsearch:
  hosts:  # set in environment settings, leave nil for development
  index_name: 'directory'

sentry:
  url: # Sentry URL goes here in settings.local.yml

roz:
  access_id: # set in settings.local.yml
  secret_key: # set in settings.local.yml

redis:
  # This is overridden in config/settings/[staging|production].yml
  url: "********************"
  name: 'wcms-publisher'

author_roles: # This could be overwritten in chef
  - employee
  - faculty
  - student
  - student worker

universe:
  development:
    academic_publisher: # set in settings.local.yml
    profile_publisher: # set in settings.local.yml
  staging:
    academic_publisher: "https://wcms.staging.biola.edu/academics"
    profile_publisher: "https://wcms.staging.biola.edu/profiles"
  production:
    academic_publisher: "https://wcms.biola.edu/academics"
    profile_publisher: "https://wcms.biola.edu/profiles"
  test:
    academic_publisher: "https://wcms.examplations.com/academics"
    profile_publisher: "https://wcms.examplations.com/profiles"

# for mongoid history -- assigns additional child object logs to be shown
trackable_relations:
  PageEdition:
    # non-embeds
    - attachments
    # embeds
    - redirect
    - audience_collection
    - permissions
  Site:
    - site_categories

audience:
  - 'Alumni'
  - 'Faculty'
  - 'General Public'
  - 'Parents'
  - 'Staff'
  - 'Students'

# Set the destination of zapier webhooks.
zapier:
  event_change_webhook_url: # set in settings.local.yml
  page_change_webhook_url: # set in settings.local.yml

# List academic years you want to import events from chapel api
chapel_import_years: []
#  - "2016-2017"

ws:
  url: https://wsdev.biola.edu
  key_path: # set in settings.local.yml
  key_password: # set in settings.local.yml
  cert_path: # set in settings.local.yml
  verify_ssl: false

ws_syncable_sites:
  - 'Biola Now'

# Classes that have aasm_states that should be auto published and archived
aasm_state_classes:
  auto_archive:
    - Article
    - PageEdition
    - Event
    - Feature
  auto_publish:
    - Article
    - PageEdition
    - Event
    - Feature

# Default contact information for chapel events
chapel:
  email: 'chapel@biola.edu'
  phone: '(562) 903-4874'

# Type specific contact information for chapel events.
# To include other types just titleize and parameterize the type here. It happens
#  dynamically in the code.
#  So AfterDark would become after_dark and Biola Hour would be biola_hour
talbot:
  email: 'catherine.m.wilson@biola.edu'
  phone: '562-944-0351 ext.5521'
