app:
  name: WCMS
  host: wcms.biola.edu
  relative_url_root:

# Overwrite this in production
secret_token:

urn_namespaces:
- "urn:biola:apps:wcms:"
- "urn:biola:apps:all:"

cas:
  url: "https://login.biola.edu/cas"

email:
  from: no-reply@biola.edu
  developer: appdev@biola.edu
  smtp:
    server: postfix.biola.edu

elasticsearch:
  hosts:  # set in environment settings, leave nil for development
  index_name: 'directory'

sentry:
  url: # Sentry URL goes here in settings.local.yml

roz:
  access_id: # set in settings.local.yml
  secret_key: # set in settings.local.yml

redis:
  # This is overridden in config/settings/[staging|production].yml
  url: "********************"
  name: 'wcms-publisher'

author_roles: # This could be overwritten in chef
  - employee
  - faculty
  - student
  - student worker

external_routes:
  academic_program: "https://wcms.biola.edu/academics/academic_programs"
  academic_subject: "https://wcms.biola.edu/academics/academic_subjects"
  department: "https://wcms.biola.edu/profiles/departments"
  event: "https://wcms.biola.edu/profiles/events"
  group: "https://wcms.biola.edu/profiles/groups"
  # Concentrations don't have their own show pages but are rather listed in academic programs
  # concentration: "https://wcms.biola.edu/academics/academic_programs"
