app:
  name: WCMS
  host: wcms.biola.edu
  relative_url_root:

# Overwrite this in production
secret_token:

urn_namespaces:
- "urn:biola:apps:wcms-publisher:"
- "urn:biola:apps:all:"

cas:
  url: "https://login.biola.edu/cas"

email:
  from: no-reply@biola.edu
  developer: appdev@biola.edu
  smtp:
    server: postfix.biola.edu

elasticsearch:
  hosts:  # set in environment settings, leave nil for development
  index_name: 'directory'

sentry:
  url: # Sentry URL goes here in settings.local.yml

roz:
  access_id: # set in settings.local.yml
  secret_key: # set in settings.local.yml

redis:
  # This is overridden in config/settings/[staging|production].yml
  url: "********************"
  name: 'wcms-publisher'

author_roles: # This could be overwritten in chef
  - employee
  - faculty
  - student
  - student worker

universe:
  development:
    academic_publisher: # set in settings.local.yml
    profile_publisher: # set in settings.local.yml
    news_publisher: # set in settings.local.yml
  staging:
    academic_publisher: "https://wcms.staging.biola.edu/academics"
    profile_publisher: "https://wcms.staging.biola.edu/profiles"
    news_publisher: "https://wcms.staging.biola.edu/news"
  production:
    academic_publisher: "https://wcms.biola.edu/academics"
    profile_publisher: "https://wcms.biola.edu/profiles"
    news_publisher: "https://wcms.biola.edu/news"
  test:
    academic_publisher: "https://wcms.examplations.com/academics"
    profile_publisher: "https://wcms.examplations.com/profiles"
    news_publisher: "https://wcms.examplations.com/news"
