app:
  name: WCMS Publisher
  host: wcms-publisher.dev
  relative_url_root: /

# Run rake secret to generate a new token
secret_token: c9db39665e0d640e41a48eac33f621ce09c2c21f795599dc77ca2d85213564ac5f577fb0a49fb17caf9dbd09278223a4a88225d7d431d7eeaa87009154925161

# This may need to be changed depending on how your are running redis locally.
redis:
  url: "redis://127.0.0.1:6379/0"

elasticsearch:
  hosts: # set in environment settings, leave nil for development
  index_name: directory

# Keep this list in alphabetical order
publishers:
  - title: Academic Programs
    url: http://academic-publisher.dev/academic_programs
  - title: Academic Subjects
    url: http://academic-publisher.dev/academic_subjects
  - class_name: Article
    title: Articles
  - title: Attachments
    url: http://academic-publisher.dev/attachments
  - class_name: Calendar
  - class_name: CampusLocation
  - title: Catalogs
    url: http://academic-publisher.dev/catalogs
  - title: Courses
    url: http://academic-publisher.dev/courses
  - title: Departments
    url: http://profile-publisher.dev/offices-services
  - class_name: Event
  - class_name: EventCollection
  - class_name: Feature
    title: Features
  - title: Forms
    url: http://forms.biola.edu/admin
  - title: Groups
    url: http://profile-publisher.dev/groups
  - class_name: ImportantDate
  - class_name: Medium
  - class_name: Menu
  - title: Outcome Pages
    url: http://academic-publisher.dev/outcome_editions
  - class_name: PageEdition
    title: Pages
  - title: People
    url: http://profile-publisher.dev/people
  - class_name: PhotoGallery
  - class_name: PresentationDataTemplate
  - title: Schools
    url: http://academic-publisher.dev/schools
  - class_name: ServiceLink
  - class_name: Site
  - title: University Learning Outcomes
    url: http://academic-publisher.dev/university_learning_outcomes
  - class_name: User
