elasticsearch:
  hosts:
  - elastic1a.prod.biola.edu
  - elastic1b.prod.biola.edu
  index_name: directory

publishers:
  - name: Academic Programs
    url: https://wcms.biola.edu/academics/academic_programs
  - name: Academic Subjects
    url: https://wcms.biola.edu/academics/academic_subjects
  - name: Articles
    url: https://wcms.biola.edu/news/articles
  - name: Attachments
    url: https://wcms.biola.edu/academics/attachments
  - name: Calendars
    url: https://wcms.biola.edu/calendars
  - name: Campus Location
    url: https://wcms.biola.edu/campus_locations
  - name: Catalogs
    url: https://wcms.biola.edu/academics/catalogs
  - name: Courses
    url: https://wcms.biola.edu/academics/courses
  - name: Data Templates
    url: https://wcms.biola.edu/academics/presentation_data_templates
  - name: Departments
    url: https://wcms.biola.edu/profiles/offices-services
  - name: Events
    url: https://wcms.biola.edu/news/events
  - name: External Articles
    url: https://wcms.biola.edu/news/external_articles
  - name: External Blogs
    url: https://wcms.biola.edu/news/external_blogs
  - name: Features
    url: https://wcms.biola.edu/news/features
  - name: Forms
    url: https://forms.biola.edu/admin
  - name: Generic Objects
    url: https://wcms.biola.edu/academics/generic_objects
  - name: Groups
    url: https://wcms.biola.edu/profiles/groups
  - name: Important Dates
    url: https://wcms.biola.edu/important_dates
  - name: Menus
    url: https://wcms.biola.edu/menus
  - name: Outcome Pages
    url: https://wcms.biola.edu/academics/outcome_editions
  - name: Page Editions
    url: https://wcms.biola.edu/page_editions
  - name: People
    url: https://wcms.biola.edu/profiles/people
  - name: Publications
    url: https://wcms.biola.edu/news/publications
  - name: Publication Categories
    url: https://wcms.biola.edu/news/publication_categories
  - name: Schools
    url: https://wcms.biola.edu/academics/schools
  - name: Service Links
    url: https://wcms.biola.edu/service_links
  - name: Sites
    url: https://wcms.biola.edu/sites
  - name: University Learning Outcomes
    url: https://wcms.biola.edu/academics/university_learning_outcomes
  - name: Users
    url: https://wcms.biola.edu/news/users
