elasticsearch:
  hosts:
  - elastic1.staging.biola.edu
  index_name: directory

publishers:
  - title: Academic Programs
    url: https://wcms.staging.biola.edu/academics/academic_programs
  - title: Academic Subjects
    url: https://wcms.staging.biola.edu/academics/academic_subjects
  - title: Articles
    url: https://wcms.staging.biola.edu/news/articles
  - title: Attachments
    url: https://wcms.staging.biola.edu/academics/attachments
  - class_name: Calendar
  - class_name: CampusLocation
  - title: Catalogs
    url: https://wcms.staging.biola.edu/academics/catalogs
  - title: Courses
    url: https://wcms.staging.biola.edu/academics/courses
  - class_name: PresentationDataTemplate
  - title: Departments
    url: https://wcms.staging.biola.edu/profiles/offices-services
  - title: Events
    url: https://wcms.staging.biola.edu/news/events
  - title: External Articles
    url: https://wcms.staging.biola.edu/news/external_articles
  - title: External Blogs
    url: https://wcms.staging.biola.edu/news/external_blogs
  - title: Features
    url: https://wcms.staging.biola.edu/news/features
  - title: Forms
    url: https://forms.biola.edu/admin
  - title: Groups
    url: https://wcms.staging.biola.edu/profiles/groups
  - class_name: ImportantDate
  - class_name: Medium
  - class_name: Menu
  - title: Outcome Pages
    url: https://wcms.staging.biola.edu/academics/outcome_editions
  - class_name: PageEdition
    title: Pages
  - title: People
    url: https://wcms.staging.biola.edu/profiles/people
  - class_name: PhotoGallery
  - title: Publications
    url: https://wcms.staging.biola.edu/news/publications
  - title: Publication Categories
    url: https://wcms.staging.biola.edu/news/publication_categories
  - title: Schools
    url: https://wcms.staging.biola.edu/academics/schools
  - class_name: ServiceLink
  - class_name: Site
  - title: University Learning Outcomes
    url: https://wcms.staging.biola.edu/academics/university_learning_outcomes
  - class_name: User
